AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::085957618812:role/service-role/AWS-CodePipeline-Service  # Replace <account-id>
      ArtifactStore:
        Type: S3
        Location: tisan-calcomartifact  # Replace with your S3 bucket name for artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: tisanbako  # Replace with GitHub owner (user or organization)
                Repo: tisan-calcom-service # Replace with your GitHub repository name
                Branch: main  # Replace with the branch to be used
                OAuthToken: <github-oauth-token>  # Replace with a GitHub OAuth token with access to the repo
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: <build-project-name>  # Replace with the name of your CodeBuild project for building
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: <deploy-project-name>  # Replace with the name of your CodeBuild project for deploying
              RunOrder: 1

  # CodeBuild project for building Docker images
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: <build-project-name>  # Replace with the name of your CodeBuild project
      Source:
        Type: CODEPIPELINE
        BuildSpec: build-config/buildspec.yml  # Ensure path is correct
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::<account-id>:role/service-role/AWS-CodeBuild-ServiceRole  # Replace <account-id>
      TimeoutInMinutes: 60

  # CodeBuild project for deploying to EKS
  DeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: <deploy-project-name>  # Replace with the name of your CodeBuild project
      Source:
        Type: CODEPIPELINE
        BuildSpec: deploy-config/deployspec.yml  # Ensure path is correct
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::<account-id>:role/service-role/AWS-CodeBuild-ServiceRole  # Replace <account-id>
      TimeoutInMinutes: 60
