AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GitHubToken:
    Type: String
    Description: 
  GitHubOwner:
    Type: String
    Description: "tisanbako" 
  GitHubRepo:
    Type: String
    Description: "tisan-calcom-service" 
  GitHubBranch:
    Type: String
    Description: "main" #
    Type: String
    Description: "" 

Resources:
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codepipeline.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CodePipelinePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:*"
                  - "codebuild:*"
                  - "codepipeline:*"
                Resource: "*"

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:*"
                  - "s3:*"
                  - "ecr:*"
                  - "ec2:*"
                  - "cloudwatch:*"
                  - "codebuild:*"
                  - "codepipeline:*"
                  - "ssm:GetParameters"
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                  - "kms:DescribeKey"
                  - "kms:ListAliases"
                  - "kms:ListKeys"
                  - "kms:CreateGrant"
                  - "kms:RetireGrant"
                Resource: "*"

  ECRRepositoryWeb:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "calcom-web" 

  ECRRepositoryAPIV1:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "calcom-api-v1"

  ECRRepositoryAPIV2:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "calcom-api-v2" 

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Sub "${AWS::StackName}-build"
      Description: "Build project for Cal.com"
      Source:
        Type: "GITHUB"
        Location: !Sub "https://github.com/tisanbako/tisan-calcom-service.git" 
        Auth:
          Resource: "arn:aws:secretsmanager:us-west-2:accountID:secret:
          Type: "OAUTH"
      Artifacts:
        Type: "S3"
        Location: !Ref tisan-calcomartifact 
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:4.0"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: "AWS_DEFAULT_REGION"
            Value: "us-west-2" 
          - Name: "ECR_REPOSITORY_WEB"
            Value: !Ref "ECRRepositoryWeb" 
          - Name: "ECR_REPOSITORY_API_V1"
            Value: !Ref "ECRRepositoryAPIV1" 
          - Name: "ECR_REPOSITORY_API_V2"
            Value: !Ref "ECRRepositoryAPIV2" 

  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub "${AWS::StackName}-pipeline"
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref tisanbako #
                Repo: !Ref tisan-calcom-service 
                Branch: !Ref main #
                OAuthToken: !Ref 
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
