AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: arn:aws:iam::<account-id>:role/service-role/AWS-CodePipeline-Service
      ArtifactStore:
        Type: S3
        Location: <your-artifact-store-bucket>
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: <github-owner>
                Repo: <github-repo>
                Branch: <branch-name>
                OAuthToken: <github-oauth-token>
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: <build-project-name>
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: <deploy-project-name>
              RunOrder: 1

  # CodeBuild project for building Docker images
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: <build-project-name>
      Source:
        Type: CODEPIPELINE
        BuildSpec: build-config/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::<account-id>:role/service-role/AWS-CodeBuild-ServiceRole
      TimeoutInMinutes: 60

  # CodeBuild project for deploying to EKS
  DeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: <deploy-project-name>
      Source:
        Type: CODEPIPELINE
        BuildSpec: deploy-config/deployspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::<account-id>:role/service-role/AWS-CodeBuild-ServiceRole
      TimeoutInMinutes: 60
