AWSTemplateFormatVersion: '2010-09-09'
Description: EKS Cluster with Fargate Profile

Resources:
  # IAM Role for EKS Cluster
  EKSClusterRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSClusterRole"  
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
        - "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"

  # IAM Role for EKS Fargate Profile
  EKSFargateRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EKSFargateRole"  
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks-fargate-pods.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy"

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: "my-eks-cluster"
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - ""  
          - ""
  FargateProfile:
    Type: "AWS::EKS::FargateProfile"
    Properties:
      ClusterName: !Ref EKSCluster
      FargateProfileName: "my-fargate-profile"
      PodExecutionRoleArn: !GetAtt EKSFargateRole.Arn
      Subnets:
        - ""  
        - ""
      Selectors:
        - Namespace: "default"

