apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-v1
  template:
    metadata:
      labels:
        app: api-v1
    spec:
      containers:
      - name: api-v1
        image: 085957618812.dkr.ecr.us-west-2.amazonaws.com/api-v1:latest
        ports:
        - containerPort: 4000

