apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-v2
  template:
    metadata:
      labels:
        app: api-v2
    spec:
      containers:
      - name: api-v2
        image: 085957618812.dkr.ecr.us-west-2.amazonaws.com/api-v2:latest
        ports:
        - containerPort: 4001

